
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/tmp/pip-build-env-t0netxfc/overlay/lib/python3.8/site-packages/cmake/data/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.10.0-051000-generic - x86_64
...
